### ISSUE TITLE
List of bugs in 2.1.3

### ISSUE THREAD

**Issue by OsipXD** [EndlessCodeGroup/RPGInventory#81]
Here will be all bugs that should be fixed in new version. 

- [x] Unknown method `getWidth()` on versions lower than 1.12 (#79)
- [x] Horrible bug on player death (#77)
- [x] Bug with item use animation (#86)
- [x] RPGInventory content is lost on death (#77)
- [x] `/heal` doesn't work (#77)
- [x] Pets despawns on cliffs (#77)
- [ ] Bug backpacks loading (#45)

**Comment by jxhxnhx** [comment]
Hello , the version 2.1.3 has a bug that if you hand a item it will jump,jump,jump. I'm so sorry my English is not very good. You can have a try in minecraft 1.12.1. I am using version 1.12.2.  Hoping you fix it !

**Comment by OsipXD** [comment]
@jxhxnhx, thanks for report

**Comment by Fargus5** [comment]
There is another bug...
Shulkerbox are in conflict with backpacks.... I've an user that  reported to me two times that when he try to put a shulkerbow into the backpack... after some time this will disappear.
Thanks in advance to let me know about this fix

**Comment by OsipXD** [comment]
@Fargus5, thanks for report
